// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: test/test.proto
//
package test

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

public class ExampleServiceClient(
  private val client: ProtocolClientInterface,
) : ExampleServiceClientInterface {
  override suspend fun exampleCall(request: Test.ExampleMessage, headers: Headers):
      ResponseMessage<Test.ExampleMessage> = client.unary(
    request,
    headers,
    MethodSpec(
    "test.ExampleService/ExampleCall",
      test.Test.ExampleMessage::class,
      test.Test.ExampleMessage::class,
      StreamType.UNARY,
    ),
  )

}
