// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test/test.proto
// Protobuf Java Version: 4.27.2

package test;

public final class Test {
  private Test() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Test.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code test.ExampleEnum}
   */
  public enum ExampleEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>VALUE_IN = 1;</code>
     */
    VALUE_IN(1),
    /**
     * <code>VALUE_OUT = 2;</code>
     */
    VALUE_OUT(2),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        ExampleEnum.class.getName());
    }
    /**
     * <code>VALUE_IN = 1;</code>
     */
    public static final int VALUE_IN_VALUE = 1;
    /**
     * <code>VALUE_OUT = 2;</code>
     */
    public static final int VALUE_OUT_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ExampleEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ExampleEnum forNumber(int value) {
      switch (value) {
        case 1: return VALUE_IN;
        case 2: return VALUE_OUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ExampleEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ExampleEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ExampleEnum>() {
            public ExampleEnum findValueByNumber(int number) {
              return ExampleEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return test.Test.getDescriptor().getEnumTypes().get(0);
    }

    private static final ExampleEnum[] VALUES = values();

    public static ExampleEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ExampleEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:test.ExampleEnum)
  }

  public interface ExampleMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.ExampleMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string not_utf8 = 1 [json_name = "notUtf8", features = { ... }</code>
     * @return The notUtf8.
     */
    java.lang.String getNotUtf8();
    /**
     * <code>string not_utf8 = 1 [json_name = "notUtf8", features = { ... }</code>
     * @return The bytes for notUtf8.
     */
    com.google.protobuf.ByteString
        getNotUtf8Bytes();

    /**
     * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
     * @return A list containing the flags.
     */
    java.util.List<java.lang.Boolean> getFlagsList();
    /**
     * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
     * @return The count of flags.
     */
    int getFlagsCount();
    /**
     * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
     * @param index The index of the element to return.
     * @return The flags at the given index.
     */
    boolean getFlags(int index);

    /**
     * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
     * @return Whether the child field is set.
     */
    boolean hasChild();
    /**
     * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
     * @return The child.
     */
    test.Test.ExampleMessage getChild();
    /**
     * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
     */
    test.Test.ExampleMessageOrBuilder getChildOrBuilder();

    /**
     * <code>.test.ExampleEnum enum = 4 [json_name = "enum", features = { ... }</code>
     * @return Whether the enum field is set.
     */
    boolean hasEnum();
    /**
     * <code>.test.ExampleEnum enum = 4 [json_name = "enum", features = { ... }</code>
     * @return The enum.
     */
    test.Test.ExampleEnum getEnum();
  }
  /**
   * Protobuf type {@code test.ExampleMessage}
   */
  public static final class ExampleMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:test.ExampleMessage)
      ExampleMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        ExampleMessage.class.getName());
    }
    // Use ExampleMessage.newBuilder() to construct.
    private ExampleMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ExampleMessage() {
      notUtf8_ = "";
      flags_ = emptyBooleanList();
      enum_ = 1;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.Test.internal_static_test_ExampleMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.Test.internal_static_test_ExampleMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.Test.ExampleMessage.class, test.Test.ExampleMessage.Builder.class);
    }

    private int bitField0_;
    public static final int NOT_UTF8_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object notUtf8_ = "";
    /**
     * <code>string not_utf8 = 1 [json_name = "notUtf8", features = { ... }</code>
     * @return The notUtf8.
     */
    @java.lang.Override
    public java.lang.String getNotUtf8() {
      java.lang.Object ref = notUtf8_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          notUtf8_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string not_utf8 = 1 [json_name = "notUtf8", features = { ... }</code>
     * @return The bytes for notUtf8.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNotUtf8Bytes() {
      java.lang.Object ref = notUtf8_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notUtf8_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLAGS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.BooleanList flags_ =
        emptyBooleanList();
    /**
     * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
     * @return A list containing the flags.
     */
    @java.lang.Override
    public java.util.List<java.lang.Boolean>
        getFlagsList() {
      return flags_;
    }
    /**
     * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
     * @return The count of flags.
     */
    public int getFlagsCount() {
      return flags_.size();
    }
    /**
     * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
     * @param index The index of the element to return.
     * @return The flags at the given index.
     */
    public boolean getFlags(int index) {
      return flags_.getBoolean(index);
    }

    public static final int CHILD_FIELD_NUMBER = 3;
    private test.Test.ExampleMessage child_;
    /**
     * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
     * @return Whether the child field is set.
     */
    @java.lang.Override
    public boolean hasChild() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
     * @return The child.
     */
    @java.lang.Override
    public test.Test.ExampleMessage getChild() {
      return child_ == null ? test.Test.ExampleMessage.getDefaultInstance() : child_;
    }
    /**
     * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
     */
    @java.lang.Override
    public test.Test.ExampleMessageOrBuilder getChildOrBuilder() {
      return child_ == null ? test.Test.ExampleMessage.getDefaultInstance() : child_;
    }

    public static final int ENUM_FIELD_NUMBER = 4;
    private int enum_ = 1;
    /**
     * <code>.test.ExampleEnum enum = 4 [json_name = "enum", features = { ... }</code>
     * @return Whether the enum field is set.
     */
    @java.lang.Override public boolean hasEnum() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.test.ExampleEnum enum = 4 [json_name = "enum", features = { ... }</code>
     * @return The enum.
     */
    @java.lang.Override public test.Test.ExampleEnum getEnum() {
      test.Test.ExampleEnum result = test.Test.ExampleEnum.forNumber(enum_);
      return result == null ? test.Test.ExampleEnum.VALUE_IN : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(notUtf8_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, notUtf8_);
      }
      for (int i = 0; i < flags_.size(); i++) {
        output.writeBool(2, flags_.getBoolean(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeGroup(3, getChild());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(4, enum_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(notUtf8_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, notUtf8_);
      }
      {
        int dataSize = 0;
        dataSize = 1 * getFlagsList().size();
        size += dataSize;
        size += 1 * getFlagsList().size();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeGroupSize(3, getChild());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, enum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.Test.ExampleMessage)) {
        return super.equals(obj);
      }
      test.Test.ExampleMessage other = (test.Test.ExampleMessage) obj;

      if (!getNotUtf8()
          .equals(other.getNotUtf8())) return false;
      if (!getFlagsList()
          .equals(other.getFlagsList())) return false;
      if (hasChild() != other.hasChild()) return false;
      if (hasChild()) {
        if (!getChild()
            .equals(other.getChild())) return false;
      }
      if (hasEnum() != other.hasEnum()) return false;
      if (hasEnum()) {
        if (enum_ != other.enum_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOT_UTF8_FIELD_NUMBER;
      hash = (53 * hash) + getNotUtf8().hashCode();
      if (getFlagsCount() > 0) {
        hash = (37 * hash) + FLAGS_FIELD_NUMBER;
        hash = (53 * hash) + getFlagsList().hashCode();
      }
      if (hasChild()) {
        hash = (37 * hash) + CHILD_FIELD_NUMBER;
        hash = (53 * hash) + getChild().hashCode();
      }
      if (hasEnum()) {
        hash = (37 * hash) + ENUM_FIELD_NUMBER;
        hash = (53 * hash) + enum_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.Test.ExampleMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.Test.ExampleMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.Test.ExampleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.Test.ExampleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.Test.ExampleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.Test.ExampleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.Test.ExampleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static test.Test.ExampleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static test.Test.ExampleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static test.Test.ExampleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.Test.ExampleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static test.Test.ExampleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.Test.ExampleMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.ExampleMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.ExampleMessage)
        test.Test.ExampleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.Test.internal_static_test_ExampleMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.Test.internal_static_test_ExampleMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.Test.ExampleMessage.class, test.Test.ExampleMessage.Builder.class);
      }

      // Construct using test.Test.ExampleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getChildFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        notUtf8_ = "";
        flags_ = emptyBooleanList();
        child_ = null;
        if (childBuilder_ != null) {
          childBuilder_.dispose();
          childBuilder_ = null;
        }
        enum_ = 1;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.Test.internal_static_test_ExampleMessage_descriptor;
      }

      @java.lang.Override
      public test.Test.ExampleMessage getDefaultInstanceForType() {
        return test.Test.ExampleMessage.getDefaultInstance();
      }

      @java.lang.Override
      public test.Test.ExampleMessage build() {
        test.Test.ExampleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.Test.ExampleMessage buildPartial() {
        test.Test.ExampleMessage result = new test.Test.ExampleMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(test.Test.ExampleMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.notUtf8_ = notUtf8_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          flags_.makeImmutable();
          result.flags_ = flags_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.child_ = childBuilder_ == null
              ? child_
              : childBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.enum_ = enum_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.Test.ExampleMessage) {
          return mergeFrom((test.Test.ExampleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.Test.ExampleMessage other) {
        if (other == test.Test.ExampleMessage.getDefaultInstance()) return this;
        if (!other.getNotUtf8().isEmpty()) {
          notUtf8_ = other.notUtf8_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.flags_.isEmpty()) {
          if (flags_.isEmpty()) {
            flags_ = other.flags_;
            flags_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureFlagsIsMutable();
            flags_.addAll(other.flags_);
          }
          onChanged();
        }
        if (other.hasChild()) {
          mergeChild(other.getChild());
        }
        if (other.hasEnum()) {
          setEnum(other.getEnum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                notUtf8_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                boolean v = input.readBool();
                ensureFlagsIsMutable();
                flags_.addBoolean(v);
                break;
              } // case 16
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                int alloc = length > 4096 ? 4096 : length;
                ensureFlagsIsMutable(alloc / 1);
                while (input.getBytesUntilLimit() > 0) {
                  flags_.addBoolean(input.readBool());
                }
                input.popLimit(limit);
                break;
              } // case 18
              case 27: {
                input.readGroup(3,
                    getChildFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 27
              case 32: {
                int tmpRaw = input.readEnum();
                test.Test.ExampleEnum tmpValue =
                    test.Test.ExampleEnum.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(4, tmpRaw);
                } else {
                  enum_ = tmpRaw;
                  bitField0_ |= 0x00000008;
                }
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object notUtf8_ = "";
      /**
       * <code>string not_utf8 = 1 [json_name = "notUtf8", features = { ... }</code>
       * @return The notUtf8.
       */
      public java.lang.String getNotUtf8() {
        java.lang.Object ref = notUtf8_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            notUtf8_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string not_utf8 = 1 [json_name = "notUtf8", features = { ... }</code>
       * @return The bytes for notUtf8.
       */
      public com.google.protobuf.ByteString
          getNotUtf8Bytes() {
        java.lang.Object ref = notUtf8_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          notUtf8_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string not_utf8 = 1 [json_name = "notUtf8", features = { ... }</code>
       * @param value The notUtf8 to set.
       * @return This builder for chaining.
       */
      public Builder setNotUtf8(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        notUtf8_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string not_utf8 = 1 [json_name = "notUtf8", features = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearNotUtf8() {
        notUtf8_ = getDefaultInstance().getNotUtf8();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string not_utf8 = 1 [json_name = "notUtf8", features = { ... }</code>
       * @param value The bytes for notUtf8 to set.
       * @return This builder for chaining.
       */
      public Builder setNotUtf8Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        notUtf8_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.BooleanList flags_ = emptyBooleanList();
      private void ensureFlagsIsMutable() {
        if (!flags_.isModifiable()) {
          flags_ = makeMutableCopy(flags_);
        }
        bitField0_ |= 0x00000002;
      }
      private void ensureFlagsIsMutable(int capacity) {
        if (!flags_.isModifiable()) {
          flags_ = makeMutableCopy(flags_, capacity);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
       * @return A list containing the flags.
       */
      public java.util.List<java.lang.Boolean>
          getFlagsList() {
        flags_.makeImmutable();
        return flags_;
      }
      /**
       * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
       * @return The count of flags.
       */
      public int getFlagsCount() {
        return flags_.size();
      }
      /**
       * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
       * @param index The index of the element to return.
       * @return The flags at the given index.
       */
      public boolean getFlags(int index) {
        return flags_.getBoolean(index);
      }
      /**
       * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
       * @param index The index to set the value at.
       * @param value The flags to set.
       * @return This builder for chaining.
       */
      public Builder setFlags(
          int index, boolean value) {

        ensureFlagsIsMutable();
        flags_.setBoolean(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
       * @param value The flags to add.
       * @return This builder for chaining.
       */
      public Builder addFlags(boolean value) {

        ensureFlagsIsMutable();
        flags_.addBoolean(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
       * @param values The flags to add.
       * @return This builder for chaining.
       */
      public Builder addAllFlags(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureFlagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, flags_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool flags = 2 [json_name = "flags", features = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearFlags() {
        flags_ = emptyBooleanList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private test.Test.ExampleMessage child_;
      private com.google.protobuf.SingleFieldBuilder<
          test.Test.ExampleMessage, test.Test.ExampleMessage.Builder, test.Test.ExampleMessageOrBuilder> childBuilder_;
      /**
       * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
       * @return Whether the child field is set.
       */
      public boolean hasChild() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
       * @return The child.
       */
      public test.Test.ExampleMessage getChild() {
        if (childBuilder_ == null) {
          return child_ == null ? test.Test.ExampleMessage.getDefaultInstance() : child_;
        } else {
          return childBuilder_.getMessage();
        }
      }
      /**
       * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
       */
      public Builder setChild(test.Test.ExampleMessage value) {
        if (childBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          child_ = value;
        } else {
          childBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
       */
      public Builder setChild(
          test.Test.ExampleMessage.Builder builderForValue) {
        if (childBuilder_ == null) {
          child_ = builderForValue.build();
        } else {
          childBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
       */
      public Builder mergeChild(test.Test.ExampleMessage value) {
        if (childBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            child_ != null &&
            child_ != test.Test.ExampleMessage.getDefaultInstance()) {
            getChildBuilder().mergeFrom(value);
          } else {
            child_ = value;
          }
        } else {
          childBuilder_.mergeFrom(value);
        }
        if (child_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
       */
      public Builder clearChild() {
        bitField0_ = (bitField0_ & ~0x00000004);
        child_ = null;
        if (childBuilder_ != null) {
          childBuilder_.dispose();
          childBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
       */
      public test.Test.ExampleMessage.Builder getChildBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getChildFieldBuilder().getBuilder();
      }
      /**
       * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
       */
      public test.Test.ExampleMessageOrBuilder getChildOrBuilder() {
        if (childBuilder_ != null) {
          return childBuilder_.getMessageOrBuilder();
        } else {
          return child_ == null ?
              test.Test.ExampleMessage.getDefaultInstance() : child_;
        }
      }
      /**
       * <code>.test.ExampleMessage child = 3 [json_name = "child", features = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          test.Test.ExampleMessage, test.Test.ExampleMessage.Builder, test.Test.ExampleMessageOrBuilder> 
          getChildFieldBuilder() {
        if (childBuilder_ == null) {
          childBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              test.Test.ExampleMessage, test.Test.ExampleMessage.Builder, test.Test.ExampleMessageOrBuilder>(
                  getChild(),
                  getParentForChildren(),
                  isClean());
          child_ = null;
        }
        return childBuilder_;
      }

      private int enum_ = 1;
      /**
       * <code>.test.ExampleEnum enum = 4 [json_name = "enum", features = { ... }</code>
       * @return Whether the enum field is set.
       */
      @java.lang.Override public boolean hasEnum() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.test.ExampleEnum enum = 4 [json_name = "enum", features = { ... }</code>
       * @return The enum.
       */
      @java.lang.Override
      public test.Test.ExampleEnum getEnum() {
        test.Test.ExampleEnum result = test.Test.ExampleEnum.forNumber(enum_);
        return result == null ? test.Test.ExampleEnum.VALUE_IN : result;
      }
      /**
       * <code>.test.ExampleEnum enum = 4 [json_name = "enum", features = { ... }</code>
       * @param value The enum to set.
       * @return This builder for chaining.
       */
      public Builder setEnum(test.Test.ExampleEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        enum_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.test.ExampleEnum enum = 4 [json_name = "enum", features = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearEnum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        enum_ = 1;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.ExampleMessage)
    }

    // @@protoc_insertion_point(class_scope:test.ExampleMessage)
    private static final test.Test.ExampleMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.Test.ExampleMessage();
    }

    public static test.Test.ExampleMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExampleMessage>
        PARSER = new com.google.protobuf.AbstractParser<ExampleMessage>() {
      @java.lang.Override
      public ExampleMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ExampleMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExampleMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.Test.ExampleMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_ExampleMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_ExampleMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017test/test.proto\022\004test\"\260\001\n\016ExampleMessa" +
      "ge\022 \n\010not_utf8\030\001 \001(\tB\005\252\001\002 \003R\007notUtf8\022\033\n\005" +
      "flags\030\002 \003(\010B\005\252\001\002\030\002R\005flags\0221\n\005child\030\003 \001(\013" +
      "2\024.test.ExampleMessageB\005\252\001\002(\002R\005child\022,\n\004" +
      "enum\030\004 \001(\0162\021.test.ExampleEnumB\005\252\001\002\010\001R\004en" +
      "um*0\n\013ExampleEnum\022\014\n\010VALUE_IN\020\001\022\r\n\tVALUE" +
      "_OUT\020\002\032\004:\002\020\0022K\n\016ExampleService\0229\n\013Exampl" +
      "eCall\022\024.test.ExampleMessage\032\024.test.Examp" +
      "leMessageBHZ?github.com/jchadwick-buf/co" +
      "nnect-editions-test/gen/go/test;test\222\003\004\010" +
      "\002(\002b\010editionsp\350\007"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_test_ExampleMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_ExampleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_ExampleMessage_descriptor,
        new java.lang.String[] { "NotUtf8", "Flags", "Child", "Enum", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
